export interface Category {
  name: string;
  controls: string[];
}

export const Settings: Category[] = [
  {name:'mouse', controls: ['MouseXMode', 'MouseXDecay', 'MouseYMode', 'MouseYDecay', 'MouseReset', 'MouseSensitivity', 'MouseDecayRate', 'MouseDeadzone', 'MouseLinearity', 'MouseGUI']},
  {name:'flightRotation', controls:['YawAxisRaw', 'YawLeftButton', 'YawRightButton', 'YawToRollMode', 'YawToRollSensitivity', 'YawToRollMode_FAOff', 'YawToRollButton', 'RollAxisRaw', 'RollLeftButton', 'RollRightButton', 'PitchAxisRaw', 'PitchUpButton', 'PitchDownButton']},
  {name:'flightThrust', controls:['LateralThrustRaw', 'LeftThrustButton', 'RightThrustButton', 'VerticalThrustRaw', 'UpThrustButton', 'DownThrustButton', 'AheadThrust', 'ForwardThrustButton', 'BackwardThrustButton']},
  {name:'flightThrottle', controls:['ThrottleAxis', 'ThrottleRange', 'ToggleReverseThrottleInput', 'ForwardKey', 'BackwardKey', 'ThrottleIncrement', 'SetSpeedMinus100', 'SetSpeedMinus75', 'SetSpeedMinus50', 'SetSpeedMinus25', 'SetSpeedZero', 'SetSpeed25', 'SetSpeed50', 'SetSpeed75', 'SetSpeed100']},
  {name:'alternateFlight', controls:['UseAlternateFlightValuesToggle', 'YawAxisAlternate', 'RollAxisAlternate', 'PitchAxisAlternate', 'LateralThrustAlternate', 'VerticalThrustAlternate']},
  {name:'flightLandingOverrides', controls:['YawAxis_Landing','YawLeftButton_Landing', 'YawRightButton_Landing', 'YawToRollMode_Landing', 'PitchAxis_Landing', 'PitchUpButton_Landing', 'PitchDownButton_Landing', 'RollAxis_Landing', 'RollLeftButton_Landing', 'RollRightButton_Landing', 'LateralThrust_Landing','LeftThrustButton_Landing', 'RightThrustButton_Landing', 'VerticalThrust_Landing', 'UpThrustButton_Landing', 'DownThrustButton_Landing', 'AheadThrust_Landing','ForwardThrustButton_Landing', 'BackwardThrustButton_Landing']},
  {name:'flightMisc', controls:['ToggleFlightAssist', 'UseBoostJuice', 'HyperSuperCombination', 'Supercruise', 'Hyperspace', 'DisableRotationCorrectToggle', 'OrbitLinesToggle']},
  {name:'targeting', controls:['SelectTarget', 'CycleNextTarget', 'CyclePreviousTarget', 'SelectHighestThreat', 'CycleNextHostileTarget', 'CyclePreviousHostileTarget', 'TargetWingman0', 'TargetWingman1', 'TargetWingman2', 'SelectTargetsTarget', 'WingNavLock', 'CycleNextSubsystem', 'CyclePreviousSubsystem', 'TargetNextRouteSystem']},
  {name:'weapons', controls:['PrimaryFire', 'SecondaryFire', 'CycleFireGroupNext', 'CycleFireGroupPrevious', 'DeployHardpointToggle', 'DeployHardpointsOnFire', 'ToggleButtonUpInput', 'DeployHeatSink']},
  {name:'misc', controls:['ShipSpotLightToggle', 'RadarRangeAxis', 'RadarIncreaseRange', 'RadarDecreaseRange', 'IncreaseEnginesPower', 'IncreaseWeaponsPower', 'IncreaseSystemsPower', 'ResetPowerDistribution', 'HMDReset', 'ToggleCargoScoop', 'EjectAllCargo', 'LandingGearToggle', 'MicrophoneMute', 'MuteButtonMode', 'CqcMuteButtonMode', 'UseShieldCell', 'FireChaffLauncher', 'ChargeECM', 'EnableRumbleTrigger', 'EnableMenuGroups', 'MouseGUI', 'WeaponColourToggle', 'EngineColourToggle', 'NightVisionToggle']},
  {name:'modeSwitches', controls:['UIFocus', 'UIFocusMode', 'FocusLeftPanel', 'FocusCommsPanel', 'FocusOnTextEntryField', 'QuickCommsPanel', 'FocusRadarPanel', 'FocusRightPanel', 'LeftPanelFocusOptions', 'CommsPanelFocusOptions', 'RolePanelFocusOptions', 'RightPanelFocusOptions', 'EnableCameraLockOn','GalaxyMapOpen', 'SystemMapOpen', 'ShowPGScoreSummaryInput', 'HeadLookToggle', 'Pause', 'FriendsMenu', 'OpenCodexGoToDiscovery', 'PlayerHUDModeToggle', 'ExplorationFSSEnter']},
  {name:'interfaceMode', controls:['UI_Up', 'UI_Down', 'UI_Left', 'UI_Right', 'UI_Select', 'UI_Back', 'UI_Toggle', 'CycleNextPanel', 'CyclePreviousPanel', 'CycleNextPage', 'CyclePreviousPage']},
  {name:'headlook', controls:['MouseHeadlook', 'MouseHeadlookInvert', 'MouseHeadlookSensitivity', 'HeadlookDefault', 'HeadlookIncrement', 'HeadlookMode', 'HeadlookResetOnToggle', 'HeadlookSensitivity', 'HeadlookSmoothing', 'HeadLookReset', 'HeadLookPitchUp', 'HeadLookPitchDown', 'HeadLookYawLeft', 'HeadLookYawRight']},
  {name:'galaxyMap', controls:['CamPitchAxis', 'CamPitchUp', 'CamPitchDown', 'CamYawAxis','CamYawLeft', 'CamYawRight', 'CamTranslateYAxis', 'CamTranslateForward', 'CamTranslateBackward', 'CamTranslateXAxis', 'CamTranslateLeft', 'CamTranslateRight', 'CamTranslateZAxis', 'CamTranslateUp', 'CamTranslateDown', 'CamZoomAxis', 'CamZoomIn', 'CamZoomOut', 'CamTranslateZHold', 'GalaxyMapHome']},
  {name:'driving', controls:['ToggleDriveAssist', 'DriveAssistDefault', 'MouseBuggySteeringXMode', 'MouseBuggySteeringXDecay', 'MouseBuggyRollingXMode', 'MouseBuggyRollingXDecay', 'MouseBuggyYMode', 'MouseBuggyYDecay', 'SteeringAxis', 'SteerLeftButton', 'SteerRightButton', 'BuggyRollAxisRaw', 'BuggyRollLeftButton', 'BuggyRollRightButton', 'BuggyPitchAxis', 'BuggyPitchUpButton', 'BuggyPitchDownButton', 'VerticalThrustersButton', 'BuggyPrimaryFireButton', 'BuggySecondaryFireButton', 'AutoBreakBuggyButton', 'HeadlightsBuggyButton', 'ToggleBuggyTurretButton', 'BuggyCycleFireGroupNext', 'BuggyCycleFireGroupPrevious']},
  {name:'drivingTargeting', controls:['SelectTarget_Buggy']},
  {name:'drivingTurret', controls:['MouseTurretXMode', 'MouseTurretXDecay', 'MouseTurretYMode', 'MouseTurretYDecay', 'BuggyTurretYawAxisRaw', 'BuggyTurretYawLeftButton', 'BuggyTurretYawRightButton', 'BuggyTurretPitchAxisRaw', 'BuggyTurretPitchUpButton', 'BuggyTurretPitchDownButton', 'BuggyTurretMouseSensitivity', 'BuggyTurretMouseDeadzone', 'BuggyTurretMouseLinearity']},
  {name:'drivingThrottle', controls:['DriveSpeedAxis', 'BuggyThrottleRange', 'BuggyToggleReverseThrottleInput', 'IncreaseSpeedButtonMax', 'DecreaseSpeedButtonMax', 'IncreaseSpeedButtonPartial', 'DecreaseSpeedButtonPartial']},
  {name:'drivingMisc', controls:['IncreaseEnginesPower_Buggy', 'IncreaseWeaponsPower_Buggy', 'IncreaseSystemsPower_Buggy', 'BuggyThrottleIncrement', 'ResetPowerDistribution_Buggy', 'ToggleCargoScoop_Buggy', 'EjectAllCargo_Buggy', 'RecallDismissShip']},
  {name:'drivingModeSwitches', controls:['UIFocus_Buggy', 'FocusLeftPanel_Buggy', 'FocusCommsPanel_Buggy', 'QuickCommsPanel_Buggy', 'FocusRadarPanel_Buggy', 'FocusRightPanel_Buggy', 'GalaxyMapOpen_Buggy', 'SystemMapOpen_Buggy', 'OpenCodexGoToDiscovery_Buggy', 'PlayerHUDModeToggle_Buggy', 'HeadLookToggle_Buggy']},
  {name:'multiCrew', controls:['MultiCrewToggleMode', 'MultiCrewPrimaryFire', 'MultiCrewSecondaryFire', 'MultiCrewPrimaryUtilityFire', 'MultiCrewSecondaryUtilityFire', 'MultiCrewThirdPersonMouseXMode', 'MultiCrewThirdPersonMouseXDecay', 'MultiCrewThirdPersonMouseYMode', 'MultiCrewThirdPersonMouseYDecay', 'MultiCrewThirdPersonYawAxisRaw', 'MultiCrewThirdPersonYawLeftButton', 'MultiCrewThirdPersonYawRightButton', 'MultiCrewThirdPersonPitchAxisRaw', 'MultiCrewThirdPersonPitchUpButton', 'MultiCrewThirdPersonPitchDownButton', 'MultiCrewThirdPersonMouseSensitivity', 'MultiCrewThirdPersonFovAxisRaw', 'MultiCrewThirdPersonFovOutButton', 'MultiCrewThirdPersonFovInButton', 'MultiCrewCockpitUICycleForward', 'MultiCrewCockpitUICycleBackward']},
  {name:'fighterOrders', controls:['OrderRequestDock', 'OrderDefensiveBehaviour', 'OrderAggressiveBehaviour', 'OrderFocusTarget', 'OrderHoldFire', 'OrderHoldPosition', 'OrderFollow', 'OpenOrders']},
  {name:'cameraSuite', controls:['PhotoCameraToggle', 'PhotoCameraToggle_Buggy', 'VanityCameraScrollLeft', 'VanityCameraScrollRight', 'ToggleFreeCam', 'VanityCameraOne', 'VanityCameraTwo', 'VanityCameraThree', 'VanityCameraFour', 'VanityCameraFive', 'VanityCameraSix', 'VanityCameraSeven', 'VanityCameraEight', 'VanityCameraNine']},
  {name:'freeCamera', controls:['FreeCamToggleHUD', 'FreeCamSpeedInc', 'FreeCamSpeedDec', 'MoveFreeCamY', 'ThrottleRangeFreeCam', 'ToggleReverseThrottleInputFreeCam', 'MoveFreeCamForward', 'MoveFreeCamBackwards', 'MoveFreeCamX', 'MoveFreeCamRight', 'MoveFreeCamLeft', 'MoveFreeCamZ', 'MoveFreeCamUpAxis', 'MoveFreeCamDownAxis', 'MoveFreeCamUp', 'MoveFreeCamDown', 'PitchCamera', 'FreeCamMouseSensitivity', 'FreeCamMouseYDecay', 'PitchCameraUp', 'PitchCameraDown', 'YawCamera', 'FreeCamMouseXDecay', 'YawCameraLeft', 'YawCameraLeft', 'RollCamera', 'RollCameraLeft', 'RollCameraRight', 'ToggleRotationLock', 'FixCameraRelativeToggle', 'FixCameraWorldToggle', 'QuitCamera', 'ToggleAdvanceMode', 'FreeCamZoomIn', 'FreeCamZoomOut', 'FStopDec', 'FStopInc']},
  {name:'storeCamera', controls:['StoreEnableRotation', 'StorePitchCamera', 'StoreYawCamera', 'StoreCamZoomIn', 'StoreCamZoomOut', 'StoreToggle']},
  {name:'holoMe', controls:['CommanderCreator_Undo', 'CommanderCreator_Redo', 'CommanderCreator_Rotation_MouseToggle', 'CommanderCreator_Rotation']},
  {name:'playlist', controls:['GalnetAudio_Play_Pause', 'GalnetAudio_SkipForward', 'GalnetAudio_SkipBackward', 'GalnetAudio_ClearQueue']},
  {name:'FSS', controls:['ExplorationFSSCameraPitch', 'ExplorationFSSCameraPitchIncreaseButton', 'ExplorationFSSCameraPitchDecreaseButton', 'ExplorationFSSCameraYaw', 'ExplorationFSSCameraYawIncreaseButton', 'ExplorationFSSCameraYawDecreaseButton', 'ExplorationFSSZoomIn', 'ExplorationFSSZoomOut', 'ExplorationFSSMiniZoomIn', 'ExplorationFSSMiniZoomOut', 'ExplorationFSSRadioTuningX_Raw', 'ExplorationFSSRadioTuningX_Increase', 'ExplorationFSSRadioTuningX_Decrease',  'ExplorationFSSRadioTuningAbsoluteX', 'ExplorationFSSDiscoveryScan', 'ExplorationFSSQuit', 'FSSMouseXMode', 'FSSMouseXDecay', 'FSSMouseYMode', 'FSSMouseYDecay', 'FSSMouseSensitivity', 'FSSMouseDeadzone', 'FSSMouseLinearity', 'ExplorationFSSTarget', 'ExplorationFSSShowHelp']},
]

export const Weirdos: Map<string,string[]> = new Map([
  ["MouseXMode",["", "Bindings_MouseRoll", "Bindings_MouseYaw"]], 
  ["MouseYMode",["", "Bindings_MousePitch", "Bindings_MousePitchInverted"]],
  ["YawToRollMode",["Bindings_YawIntoRollNone", "Bindings_YawIntoRollTime", "Bindings_YawIntoRollLowRoll"]],
  ["YawToRollMode_FAOff",["", "Bindings_YawIntoRollNone", "Bindings_YawIntoRollTime", "Bindings_YawIntoRollLowRoll"]],
  ["ThrottleRange",["", "Bindings_ThrottleForewardOnly"]],
  ["ThrottleIncrement",["0.0", "0.1", "0.125", "0.167", "0.25"]],
  ["YawToRollMode_Landing",["", "Bindings_YawIntoRollNone", "Bindings_YawIntoRollTime", "Bindings_YawIntoRollLowRoll"]],
  ["MuteButtonMode",["mute_toggle", "mute_pushToTalk", "mute_pushToMute"]],
  ["CqcMuteButtonMode",["mute_toggle", "mute_pushToTalk", "mute_pushToMute"]],
  ["UIFocusMode",["Bindings_FocusModeHold", "Bindings_FocusModeToggle"]],
  ["LeftPanelFocusOptions",["", "FocusOption_Nothing"]],
  ["CommsPanelFocusOptions",["", "FocusOptions_Show", "FocusOptions_Nothing"]],
  ["RolePanelFocusOptions",["", "FocusOptions_Nothing"]],
  ["RightPanelFocusOptions",["", "FocusOptions_Nothing"]],
  ["HeadlookIncrement",["0.0", "0.25", "0.3334", "0.5"]],
  ["HeadlookMode",["Bindings_HeadlookModeAccumulate", "Bindings_HeadlookModeDirect"]],
  ["MouseBuggyYMode",["", "Bindings_MousePitch", "Bindings_MousePitchInverted"]],
  ["MouseTurretXMode",["", "Bindings_MouseYaw"]],
  ["MouseTurretYMode",["", "Bindings_MousePitch", "Bindings_MousePitchInverted"]],
  ["BuggyThrottleRange",["", "Bindings_BuggyThrottleForwardOnly"]],
  ["BuggyThrottleIncrement",["0.0", "0.1", "0.125", "0.167", "0.25"]],
  ["MultiCrewThirdPersonMouseXMode",["", "Bindings_MouseYaw"]],
  ["MultiCrewThirdPersonMouseYMode",["", "Bindings_MousePitch", "Bindings_MousePitchInverted"]],
  ["ThrottleRangeFreeCam",["", "Bindings_ThrottleForewardOnlyFreeCam"]],
  ["PitchCameraMouse",["", "Bindings_MousePitch", "Bindings_MousePitchInverted"]],
  ["YawCameraMouse",["", "Bindings_MouseRoll", "Bindings_MouseYaw"]],
  ["FSSMouseXMode",["", "Bindings_MouseYaw"]],
  ["FSSMouseYMode",["", "Bindings_MousePitch", "Bindings_MousePitchInverted"]],
  ["SAAThirdPersonMouseXMode",["", "Bindings_MouseYaw"]],
  ["SAAThirdPersonMouseYMode",["", "Bindings_MousePitch", "Bindings_MousePitchInverted"]]
])