
export interface Key {
    name: string,
    coord: number[]
}

export const usLayout:Map<string, Key> = new Map([
    // ['keyname',{ name: 'keyDisplayName', coord: [Not Used, Not Used, Gap, Width,]}]
    ['Key_esc',{ name: 'esc', coord: [1, 1, 6, 4]}],
    ['Key_F1',{ name: 'F1', coord: [1, 2, 1, 4]}],
    ['Key_F2',{ name: 'F2', coord: [1, 3, 1, 4]}],
    ['Key_F3',{ name: 'F3', coord: [1, 4, 1, 4]}],
    ['Key_F4',{ name: 'F4', coord: [1, 5, 3, 4]}],
    ['Key_F5',{ name: 'F5', coord: [1, 6, 1, 4]}],
    ['Key_F6',{ name: 'F6', coord: [1, 7, 1, 4]}],
    ['Key_F7',{ name: 'F7', coord: [1, 8, 1, 4]}],
    ['Key_F8',{ name: 'F8', coord: [1, 9, 3, 4]}],
    ['Key_F9',{ name: 'F9', coord: [1, 10, 1, 4]}],
    ['Key_F10',{ name: 'F10', coord: [1, 11, 1, 4]}],
    ['Key_F11',{ name: 'F11', coord:  [1, 12, 1, 4]}],
    ['Key_F12',{ name: 'F12', coord: [1, 13, 2, 4]}],
    ['Key_prtsc',{ name: 'prt sc', coord: [1, 14, 1, 4]}],
    ['Key_scrlk',{ name: 'scr lk', coord: [1, 15, 1, 4]}],
    ['Key_pause',{ name: 'pause', coord: [1, 16, 1, 4]}],
    ['Key_tilde',{ name: '`', coord: [2, 1, 1, 4]}],
    ['Key_1',{ name: '1', coord: [2, 2, 1, 4]}],
    ['Key_2',{ name: '2', coord: [2, 3, 1, 4]}],
    ['Key_3',{ name: '3', coord: [2, 4, 1, 4]}],
    ['Key_4',{ name: '4', coord: [2, 5, 1, 4]}],
    ['Key_5',{ name: '5', coord: [2, 6, 1, 4]}],
    ['Key_6',{ name: '6', coord: [2, 7, 1, 4]}],
    ['Key_7',{ name: '7', coord: [2, 8, 1, 4]}],
    ['Key_8',{ name: '8', coord: [2, 9, 1, 4]}],
    ['Key_9',{ name: '9', coord: [2, 10, 1, 4]}],
    ['Key_0',{ name: '0', coord: [2, 11, 1, 4]}],
    ['Key_hyphen',{ name: '-', coord: [2, 12, 1, 4]}],
    ['Key_equals',{ name: '=', coord: [2, 13, 1, 4]}],
    ['Key_backspace',{ name: 'backspace', coord: [2, 14, 2, 8]}],
    ['Key_ins',{ name: 'ins', coord: [2, 15, 1, 4]}],
    ['Key_home',{ name: 'home', coord: [2, 16, 1, 4]}],
    ['Key_pageup',{ name: 'page up', coord: [2, 17, 1, 4]}],
    ['Key_tab',{ name: 'tab', coord: [3, 1, 1, 6]}],
    ['Key_q',{ name: 'q', coord: [3, 2, 1, 4]}],
    ['Key_w',{ name: 'w', coord: [3, 3, 1, 4]}],
    ['Key_e',{ name: 'e', coord: [3, 4, 1, 4]}],
    ['Key_r',{ name: 'r', coord: [3, 5, 1, 4]}],
    ['Key_t',{ name: 't', coord: [3, 6, 1, 4]}],
    ['Key_y',{ name: 'y', coord: [3, 7, 1, 4]}],
    ['Key_u',{ name: 'u', coord: [3, 8, 1, 4]}],
    ['Key_i',{ name: 'i', coord: [3, 9, 1, 4]}],
    ['Key_o',{ name: 'o', coord: [3, 10, 1, 4]}],
    ['Key_p',{ name: 'p', coord: [3, 11, 1, 4]}],
    ['Key_[',{ name: '[', coord: [3, 12, 1, 4]}],
    ['Key_]',{ name: ']', coord: [3, 13, 1, 4]}],
    ['Key_backslash',{ name: '\\', coord: [3, 14, 2, 6]}],
    ['Key_del',{ name: 'del', coord: [3, 15, 1, 4]}],
    ['Key_end',{ name: 'end', coord: [3, 16, 1, 4]}],
    ['Key_pagedown',{ name: 'page down', coord: [3, 17, 1, 4]}],
    ['Key_caps',{ name: 'caps', coord: [4, 1, 1, 7]}],
    ['Key_a',{ name: 'a', coord: [4, 2, 1, 4]}],
    ['Key_s',{ name: 's', coord: [4, 3, 1, 4]}],
    ['Key_d',{ name: 'd', coord: [4, 4, 1, 4]}],
    ['Key_f',{ name: 'f', coord: [4, 5, 1, 4]}],
    ['Key_g',{ name: 'g', coord: [4, 6, 1, 4]}],
    ['Key_h',{ name: 'h', coord: [4, 7, 1, 4]}],
    ['Key_j',{ name: 'j', coord: [4, 8, 1, 4]}],
    ['Key_k',{ name: 'k', coord: [4, 9, 1, 4]}],
    ['Key_l',{ name: 'l', coord: [4, 10, 1, 4]}],
    ['Key_;',{ name: ';', coord: [4, 11, 1, 4]}],
    ['Key_apostrophe',{ name: '\'', coord: [4, 12, 1, 4]}],
    ['Key_enter',{ name: 'enter', coord: [4, 13, 15, 10]}],
    ['Key_lShift',{ name: 'shift', coord: [5, 1, 1, 10]}],
    ['Key_z',{ name: 'z', coord: [5, 2, 1, 4]}],
    ['Key_x',{ name: 'x', coord: [5, 3, 1, 4]}],
    ['Key_c',{ name: 'c', coord: [5, 4, 1, 4]}],
    ['Key_v',{ name: 'v', coord: [5, 5, 1, 4]}],
    ['Key_b',{ name: 'b', coord: [5, 6, 1, 4]}],
    ['Key_n',{ name: 'n', coord: [5, 7, 1, 4]}],
    ['Key_m',{ name: 'm', coord: [5, 8, 1, 4]}],
    ['Key_,',{ name: ',', coord: [5, 9, 1, 4]}],
    ['Key_.',{ name: '.', coord: [5, 10, 1, 4]}],
    ['Key_/',{ name: '/', coord: [5, 11, 1, 4]}],
    ['Key_rShift',{ name: 'shift', coord: [5, 12, 7, 12]}],
    ['Key_upArrow',{ name: '^', coord: [5, 13, 6, 4]}],
    ['Key_lCtrl',{ name: 'ctrl', coord: [6, 1, 1, 5]}],
    ['Key_lWin',{ name: 'Win', coord: [6, 2, 1, 5]}],
    ['Key_lAlt',{ name: 'alt', coord: [6, 3, 1, 5]}],
    ['Key_space',{ name: 'space', coord: [6, 4, 1, 25]}],
    ['Key_rAlt',{ name: 'alt', coord: [6, 5, 1, 5]}],
    ['Key_fn',{ name: 'fn', coord: [6, 6, 1, 5]}],
    ['Key_rWin',{ name: 'Win', coord: [6, 7, 1, 5]}],
    ['Key_rCtrl',{ name: 'ctrl', coord: [6, 8, 8, 5]}],
    ['Key_leftArrow',{ name: '<', coord: [6, 9, 1, 4]}],
    ['Key_downArrow',{ name: '⌄', coord: [6, 10, 1, 4]}],
    ['Key_rightArrow',{ name: '>', coord: [6, 11, 1, 4]}],
])

export const usNumPad:Map<string, Key> = new Map([
    // ['keyname',{ name: 'keyDisplayName', coord: [Not Used, Not Used, Gap, Width,]}]
    ['Key_numlk',{ name: 'num lock', coord: [1, 1, 1, 4]}],
    ['Key_numslash',{ name: '/', coord: [1, 2, 1, 4]}],
    ['Key_numstar',{ name: '*', coord: [1, 3, 1, 4]}],
    ['Key_numhyphen',{ name: '-', coord: [1, 4, 1, 4]}],
    ['Key_num7',{ name: '7', coord: [2, 1, 1, 4]}],
    ['Key_num8',{ name: '8', coord: [2, 2, 1, 4]}],
    ['Key_num9',{ name: '9', coord: [2, 3, 1, 4]}],
    ['Key_numplus',{ name: '+', coord: [2, 4, 2, 4]}],
    ['Key_num4',{ name: '4', coord: [3, 1, 1, 4]}],
    ['Key_num5',{ name: '5', coord: [3, 2, 1, 4]}],
    ['Key_num6',{ name: '6', coord: [3, 3, 1, 4]}],
    ['Key_num1',{ name: '1', coord: [4, 1, 1, 4]}],
    ['Key_num2',{ name: '2', coord: [4, 2, 1, 4]}],
    ['Key_num3',{ name: '3', coord: [4, 3, 1, 4]}],
    ['Key_numEnter',{ name: 'enter', coord: [4, 4, 15, 4]}],
    ['Key_num0',{ name: '0', coord: [5, 1, 1, 2]}],
    ['Key_numDel',{ name: '.', coord: [5, 2, 1, 4]}],
])